# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portSelectUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_portSelect(object):
    def setupUi(self, portSelect):
        portSelect.setObjectName("portSelect")
        portSelect.resize(317, 204)
        portSelect.setStyleSheet("background-color: rgb(34, 34, 60);")
        self.centralwidget = QtWidgets.QWidget(portSelect)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    color:rgb(46,52,64);\n"
"    background-color: rgb(46,52,64);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(216,222,233);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        self.comboBox_port_sel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_port_sel.setStyleSheet("QComboBox{\n"
"    color: rgb(216,222,233);\n"
"    background-color: rgb(59,66,82);\n"
"    border: 2px solid;\n"
"    border-color: rgb(67,76,94);\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(76,86,106);\n"
"    selection-background-color: rgb(59,66,82);\n"
"    color:rgb(216,222,233);\n"
"    padding: 1px 2px 1px 2px;\n"
"}")
        self.comboBox_port_sel.setObjectName("comboBox_port_sel")
        self.gridLayout.addWidget(self.comboBox_port_sel, 2, 3, 1, 2)
        self.label_dev_port = QtWidgets.QLabel(self.centralwidget)
        self.label_dev_port.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding:10px;")
        self.label_dev_port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dev_port.setObjectName("label_dev_port")
        self.gridLayout.addWidget(self.label_dev_port, 2, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.label_port_sel_stat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_port_sel_stat.setFont(font)
        self.label_port_sel_stat.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_port_sel_stat.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_port_sel_stat.setObjectName("label_port_sel_stat")
        self.gridLayout.addWidget(self.label_port_sel_stat, 1, 1, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 1, 1, 1)
        self.button_select_port = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_port.setStyleSheet("QPushButton{\n"
"    color: rgb(216,222,233);\n"
"    border-radius: 2px;\n"
"    border: 2px;\n"
"    border: 2px solid;\n"
"    border-color: rgb(67,76,94);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(229,233,244);\n"
"    background-color: rgb(76,86,106);\n"
"    border-radius: 2px;\n"
"    border: 2px;\n"
"    border: 2px solid;\n"
"    border-color: rgb(67,76,94);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgb(229,233,244);\n"
"    background-color:rgb(67,76,94);\n"
"    border-radius: 2px;\n"
"    border: 2px;\n"
"    border: 2px solid;\n"
"    border-color: rgb(67,76,94);\n"
"    padding: 5px;\n"
"}")
        self.button_select_port.setObjectName("button_select_port")
        self.gridLayout.addWidget(self.button_select_port, 5, 3, 1, 2)
        portSelect.setCentralWidget(self.centralwidget)

        self.retranslateUi(portSelect)
        QtCore.QMetaObject.connectSlotsByName(portSelect)

    def retranslateUi(self, portSelect):
        _translate = QtCore.QCoreApplication.translate
        portSelect.setWindowTitle(_translate("portSelect", "MainWindow"))
        self.label_dev_port.setText(_translate("portSelect", "Select port"))
        self.label_port_sel_stat.setText(_translate("portSelect", "Data Logger port selection"))
        self.button_select_port.setText(_translate("portSelect", "Continue"))
